const daftarKomentar = [
    "Wah bagus banget videonya! 👍",
    "Anak saya betah nonton ini terus.",
    "Liriknya mudah dihafal, kreatif banget!",
    "Request lagu hewan lainnya dong min..",
    "Animasi videonya lucu sekali!",
    "Bermanfaat banget buat edukasi anak balita.",
    "Kualitas suaranya jernih, suka banget!",
    "Keluarga kami suka dengerin ini bareng-bareng.",
    "Visualnya cerah, cocok buat mata anak-anak.",
    "Bantu banget buat ngenalin warna ke anak saya.",
    "Ada versi bahasa Inggrisnya nggak ya?",
    "Konten yang sangat mendidik, terima kasih!",
    "Lagu favorit anak saya sebelum tidur nih.",
    "Gambarnya lucu-lucu, karakternya menggemaskan.",
    "Suara penyanyinya lembut, enak didengar.",
    "Ditunggu konten-konten baru selanjutnya ya!",
    "Setiap pagi anak saya minta diputar video ini.",
    "Bagus untuk melatih daya ingat anak lewat lagu.",
    "Sangat menghibur sekaligus mengedukasi.",
    "Anak saya langsung joget-joget pas denger lagunya! 😂",
    "Pengemasan materinya simpel tapi dapet banget.",
    "Video paling bersih dan ramah anak yang saya temukan.",
    "Keren, animasinya halus banget pergerakannya.",
    "Liriknya sangat positif, mendidik sekali.",
    "Belajar jadi lebih menyenangkan lewat video ini.",
    "Anak saya jadi lebih cepat hafal nama-nama hewan.",
    "Semoga channel ini makin berkembang ya!",
    "Konten berkualitas begini harus banyak didukung.",
    "Iramanya asik, saya yang dewasa aja ikut nyanyi haha.",
    "Bantu anak belajar bicara dengan kosa kata baru.",
    "Warna-warnanya bagus, anak saya jadi gak rewel.",
    "Terima kasih sudah buat video bermanfaat ini.",
    "Tolong buatkan lagu tentang tata krama ya min.",
    "Bagus buat stimulasi motorik anak juga nih.",
    "Anak saya langsung hapal gerakannya, lucu banget!",
    "Visualisasinya sangat membantu pemahaman anak.",
    "Sangat direkomendasikan buat orang tua di rumah.",
    "Lagu yang ceria dan penuh pesan moral.",
    "Pilihan kata-katanya sangat pas buat balita.",
    "Channel favorit keluarga kami saat ini! ⭐⭐⭐⭐⭐"
];
